# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fiser_fixed_acc/fiser_fixed_acc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc || ORIG_REF_NAME==fiser_fixed_acc} -quiet] -quiet

# IP: bd/fiser_fixed_acc/ip/fiser_fixed_acc_processing_system7_0_0/fiser_fixed_acc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc_processing_system7_0_0 || ORIG_REF_NAME==fiser_fixed_acc_processing_system7_0_0} -quiet] -quiet

# IP: bd/fiser_fixed_acc/ip/fiser_fixed_acc_fisr_fixed_ip_0_0/fiser_fixed_acc_fisr_fixed_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc_fisr_fixed_ip_0_0 || ORIG_REF_NAME==fiser_fixed_acc_fisr_fixed_ip_0_0} -quiet] -quiet

# IP: bd/fiser_fixed_acc/ip/fiser_fixed_acc_ps7_0_axi_periph_0/fiser_fixed_acc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc_ps7_0_axi_periph_0 || ORIG_REF_NAME==fiser_fixed_acc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fiser_fixed_acc/ip/fiser_fixed_acc_rst_ps7_0_100M_0/fiser_fixed_acc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc_rst_ps7_0_100M_0 || ORIG_REF_NAME==fiser_fixed_acc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/fiser_fixed_acc/ip/fiser_fixed_acc_auto_pc_0/fiser_fixed_acc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fiser_fixed_acc_auto_pc_0 || ORIG_REF_NAME==fiser_fixed_acc_auto_pc_0} -quiet] -quiet

# XDC: bd/fiser_fixed_acc/fiser_fixed_acc_ooc.xdc
