# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/fast_inverse_square_root_acc/fast_inverse_square_root_acc.srcs/sources_1/bd/fiser_fixed_acc/ip/fiser_fixed_acc_processing_system7_0_0/fiser_fixed_acc_processing_system7_0_0.xci
# IP: The module: 'fiser_fixed_acc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/fast_inverse_square_root_acc/fast_inverse_square_root_acc.srcs/sources_1/bd/fiser_fixed_acc/ip/fiser_fixed_acc_processing_system7_0_0/fiser_fixed_acc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fiser_fixed_acc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Projects/fast_inverse_square_root_acc/fast_inverse_square_root_acc.srcs/sources_1/bd/fiser_fixed_acc/ip/fiser_fixed_acc_processing_system7_0_0/fiser_fixed_acc_processing_system7_0_0.xci
# IP: The module: 'fiser_fixed_acc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/fast_inverse_square_root_acc/fast_inverse_square_root_acc.srcs/sources_1/bd/fiser_fixed_acc/ip/fiser_fixed_acc_processing_system7_0_0/fiser_fixed_acc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fiser_fixed_acc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
