# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0.xci
# IP: The module: 'mb_fisr_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0.xci
# IP: The module: 'mb_fisr_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/fast_inverse_square_root/fast_inverse_square_root.srcs/sources_1/bd/mb_fisr/ip/mb_fisr_microblaze_0_0/mb_fisr_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_fisr_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
